package com.ldp.reader.algorithmtest.source

data class BatchNovelTarget(
    val title: String,
    val author: String,
    val kind: BatchNovelKind
)

enum class BatchNovelKind {
    SERIAL,
    COMPLETED
}

object BatchNovelTargets {
    val serial: List<BatchNovelTarget> = listOf(
        BatchNovelTarget("我在修仙界万古长青", "快餐店", BatchNovelKind.SERIAL),
        BatchNovelTarget("玄鉴仙族", "季越人", BatchNovelKind.SERIAL),
        BatchNovelTarget("道爷要飞升", "裴屠狗", BatchNovelKind.SERIAL),
        BatchNovelTarget("从水猴子开始成神", "甲壳蚁", BatchNovelKind.SERIAL),
        BatchNovelTarget("神话之后", "鹅是老五", BatchNovelKind.SERIAL),
        BatchNovelTarget("仙工开物", "蛊真人", BatchNovelKind.SERIAL),
        BatchNovelTarget("阵问长生", "观虚", BatchNovelKind.SERIAL),
        BatchNovelTarget("大道之上", "宅猪", BatchNovelKind.SERIAL),
        BatchNovelTarget("谁让他修仙的！", "最白的乌鸦", BatchNovelKind.SERIAL),
        BatchNovelTarget("御兽从零分开始", "给我加葱", BatchNovelKind.SERIAL),
        BatchNovelTarget("苟在初圣魔门当人材", "鹤守月满池", BatchNovelKind.SERIAL),
        BatchNovelTarget("长生从炼丹宗师开始", "雨去欲续", BatchNovelKind.SERIAL),
        BatchNovelTarget("高武纪元", "烽仙", BatchNovelKind.SERIAL),
        BatchNovelTarget("吞噬星空2起源大陆", "我吃西红柿", BatchNovelKind.SERIAL),
        BatchNovelTarget("夜无疆", "辰东", BatchNovelKind.SERIAL),
        BatchNovelTarget("叩问仙道", "雨打青石", BatchNovelKind.SERIAL),
        BatchNovelTarget("苟在武道世界成圣", "在水中的纸老虎", BatchNovelKind.SERIAL),
        BatchNovelTarget("苟在两界修仙", "文抄公", BatchNovelKind.SERIAL),
        BatchNovelTarget("没钱修什么仙？", "熊狼狗", BatchNovelKind.SERIAL),
        BatchNovelTarget("苟在异界问长生", "孤剑行天下", BatchNovelKind.SERIAL),
        BatchNovelTarget("仙人消失之后", "风行水云间", BatchNovelKind.SERIAL),
        BatchNovelTarget("从赘婿开始建立长生家族", "天弦画柱", BatchNovelKind.SERIAL),
        BatchNovelTarget("旧域怪诞", "狐尾的笔", BatchNovelKind.SERIAL),
        BatchNovelTarget("异度旅社", "远瞳", BatchNovelKind.SERIAL),
        BatchNovelTarget("一龙一剑一神尊", "小小八", BatchNovelKind.SERIAL),
        BatchNovelTarget("一龙之力", "小卒没过河", BatchNovelKind.SERIAL),
        BatchNovelTarget("以神通之名", "猪心虾仁", BatchNovelKind.SERIAL),
        BatchNovelTarget("天倾之后", "佛前献花", BatchNovelKind.SERIAL),
        BatchNovelTarget("混在末日，独自成仙", "言归正传", BatchNovelKind.SERIAL),
        BatchNovelTarget("从婴儿开始入道", "古羲", BatchNovelKind.SERIAL),
        BatchNovelTarget("这个武圣血条太厚", "不会飞的笔", BatchNovelKind.SERIAL),
        BatchNovelTarget("剑出衡山", "一片苏叶", BatchNovelKind.SERIAL),
        BatchNovelTarget("太一道果", "衔雨", BatchNovelKind.SERIAL),
        BatchNovelTarget("法力无边高大仙", "踏雪真人", BatchNovelKind.SERIAL),
        BatchNovelTarget("山河志异", "瑞根", BatchNovelKind.SERIAL),
        BatchNovelTarget("北宋穿越指南", "王梓钧", BatchNovelKind.SERIAL),
        BatchNovelTarget("谁教你这么御兽的", "二次下海", BatchNovelKind.SERIAL),
        BatchNovelTarget("旧神之巅", "育", BatchNovelKind.SERIAL),
        BatchNovelTarget("牧者密续", "不祈十弦", BatchNovelKind.SERIAL),
        BatchNovelTarget("我不是戏神", "三九音域", BatchNovelKind.SERIAL),
        BatchNovelTarget("临渊行", "宅猪", BatchNovelKind.SERIAL),
        BatchNovelTarget("踏星", "随散飘风", BatchNovelKind.SERIAL),
        BatchNovelTarget("执魔", "我是墨水", BatchNovelKind.SERIAL),
        BatchNovelTarget("盖世双谐", "三天两觉", BatchNovelKind.SERIAL),
        BatchNovelTarget("赤侠", "红烧大黑鱼", BatchNovelKind.SERIAL),
        BatchNovelTarget("十日终焉", "杀虫队队员", BatchNovelKind.SERIAL),
        BatchNovelTarget("一剑霸天", "永夜星河", BatchNovelKind.SERIAL),
        BatchNovelTarget("光阴之外", "耳根", BatchNovelKind.SERIAL),
        BatchNovelTarget("大不列颠之影", "趋时", BatchNovelKind.SERIAL),
        BatchNovelTarget("贫道略通拳脚", "九月当归", BatchNovelKind.SERIAL),
        BatchNovelTarget("剑来", "烽火戏诸侯", BatchNovelKind.SERIAL),
        BatchNovelTarget("赘婿", "愤怒的香蕉", BatchNovelKind.SERIAL),
        BatchNovelTarget("临高启明", "吹牛者", BatchNovelKind.SERIAL),
        BatchNovelTarget("地煞七十二变", "祭酒", BatchNovelKind.SERIAL),
        BatchNovelTarget("从姑获鸟开始", "活儿该", BatchNovelKind.SERIAL),
        BatchNovelTarget("我有一个修仙世界", "纯九莲宝灯", BatchNovelKind.SERIAL),
        BatchNovelTarget("神农道君", "神威校尉", BatchNovelKind.SERIAL),
        BatchNovelTarget("长生：从气运词条开始", "江上景", BatchNovelKind.SERIAL),
        BatchNovelTarget("不是吧君子也防", "阳小戎", BatchNovelKind.SERIAL),
        BatchNovelTarget("阴影帝国", "三脚架", BatchNovelKind.SERIAL),
        BatchNovelTarget("仙父", "言归正传", BatchNovelKind.SERIAL),
        BatchNovelTarget("神秘复苏", "佛前献花", BatchNovelKind.SERIAL),
        BatchNovelTarget("这游戏也太真实了", "晨星LL", BatchNovelKind.SERIAL),
        BatchNovelTarget("从斩妖除魔开始长生不死", "陆月十九", BatchNovelKind.SERIAL),
        BatchNovelTarget("这个明星合法但有病", "冥王星话事人", BatchNovelKind.SERIAL),
        BatchNovelTarget("文娱之我只是个演员", "我就是红", BatchNovelKind.SERIAL),
        BatchNovelTarget("我在精神病院学斩神", "三九音域", BatchNovelKind.SERIAL),
        BatchNovelTarget("星河之上", "柳下挥", BatchNovelKind.SERIAL),
        BatchNovelTarget("我不是赛博精神病", "板斧战士", BatchNovelKind.SERIAL),
        BatchNovelTarget("我打造了旧日支配者神话", "金色梦乡", BatchNovelKind.SERIAL),
        BatchNovelTarget("隐秘死角", "滚开", BatchNovelKind.SERIAL),
        BatchNovelTarget("十方武圣", "滚开", BatchNovelKind.SERIAL),
        BatchNovelTarget("我的模拟长生路", "愤怒的乌贼", BatchNovelKind.SERIAL),
        BatchNovelTarget("诸界末日在线", "烟火成城", BatchNovelKind.SERIAL),
        BatchNovelTarget("灾厄收容所", "幻梦猎人", BatchNovelKind.SERIAL),
        BatchNovelTarget("全球进化后我站在食物链顶端", "七流", BatchNovelKind.SERIAL),
        BatchNovelTarget("不科学御兽", "轻泉流响", BatchNovelKind.SERIAL),
        BatchNovelTarget("宠兽之主", "黑椒仙人", BatchNovelKind.SERIAL),
        BatchNovelTarget("我师兄实在太稳健了", "言归正传", BatchNovelKind.SERIAL)
    )

    val completed: List<BatchNovelTarget> = listOf(
        BatchNovelTarget("我的诡异人生", "白刃斩春风", BatchNovelKind.COMPLETED),
        BatchNovelTarget("赤心巡天", "情何以甚", BatchNovelKind.COMPLETED),
        BatchNovelTarget("万相之王", "天蚕土豆", BatchNovelKind.COMPLETED),
        BatchNovelTarget("宿命之环", "爱潜水的乌贼", BatchNovelKind.COMPLETED),
        BatchNovelTarget("深海余烬", "远瞳", BatchNovelKind.COMPLETED),
        BatchNovelTarget("凡人修仙传", "忘语", BatchNovelKind.COMPLETED),
        BatchNovelTarget("凡人修仙之仙界篇", "忘语", BatchNovelKind.COMPLETED),
        BatchNovelTarget("诡秘之主", "爱潜水的乌贼", BatchNovelKind.COMPLETED),
        BatchNovelTarget("长夜余火", "爱潜水的乌贼", BatchNovelKind.COMPLETED),
        BatchNovelTarget("奥术神座", "爱潜水的乌贼", BatchNovelKind.COMPLETED),
        BatchNovelTarget("一世之尊", "爱潜水的乌贼", BatchNovelKind.COMPLETED),
        BatchNovelTarget("道诡异仙", "狐尾的笔", BatchNovelKind.COMPLETED),
        BatchNovelTarget("修真四万年", "卧牛真人", BatchNovelKind.COMPLETED),
        BatchNovelTarget("黎明之剑", "远瞳", BatchNovelKind.COMPLETED),
        BatchNovelTarget("异常生物见闻录", "远瞳", BatchNovelKind.COMPLETED),
        BatchNovelTarget("择日飞升", "宅猪", BatchNovelKind.COMPLETED),
        BatchNovelTarget("牧神记", "宅猪", BatchNovelKind.COMPLETED),
        BatchNovelTarget("遮天", "辰东", BatchNovelKind.COMPLETED),
        BatchNovelTarget("完美世界", "辰东", BatchNovelKind.COMPLETED),
        BatchNovelTarget("斗破苍穹", "天蚕土豆", BatchNovelKind.COMPLETED),
        BatchNovelTarget("大奉打更人", "卖报小郎君", BatchNovelKind.COMPLETED),
        BatchNovelTarget("灵境行者", "卖报小郎君", BatchNovelKind.COMPLETED),
        BatchNovelTarget("第一序列", "会说话的肘子", BatchNovelKind.COMPLETED),
        BatchNovelTarget("大王饶命", "会说话的肘子", BatchNovelKind.COMPLETED),
        BatchNovelTarget("夜的命名术", "会说话的肘子", BatchNovelKind.COMPLETED),
        BatchNovelTarget("全球高武", "老鹰吃小鸡", BatchNovelKind.COMPLETED),
        BatchNovelTarget("万族之劫", "老鹰吃小鸡", BatchNovelKind.COMPLETED),
        BatchNovelTarget("星门", "老鹰吃小鸡", BatchNovelKind.COMPLETED),
        BatchNovelTarget("深空彼岸", "辰东", BatchNovelKind.COMPLETED),
        BatchNovelTarget("圣墟", "辰东", BatchNovelKind.COMPLETED),
        BatchNovelTarget("武动乾坤", "天蚕土豆", BatchNovelKind.COMPLETED),
        BatchNovelTarget("大主宰", "天蚕土豆", BatchNovelKind.COMPLETED),
        BatchNovelTarget("元尊", "天蚕土豆", BatchNovelKind.COMPLETED),
        BatchNovelTarget("吞噬星空", "我吃西红柿", BatchNovelKind.COMPLETED),
        BatchNovelTarget("盘龙", "我吃西红柿", BatchNovelKind.COMPLETED),
        BatchNovelTarget("莽荒纪", "我吃西红柿", BatchNovelKind.COMPLETED),
        BatchNovelTarget("沧元图", "我吃西红柿", BatchNovelKind.COMPLETED),
        BatchNovelTarget("修真聊天群", "圣骑士的传说", BatchNovelKind.COMPLETED),
        BatchNovelTarget("全职高手", "蝴蝶蓝", BatchNovelKind.COMPLETED),
        BatchNovelTarget("惊悚乐园", "三天两觉", BatchNovelKind.COMPLETED)
    )

    val all: List<BatchNovelTarget> = serial + completed
}
